import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import outputs from '../../amplify_outputs.json'
import './globals.css'
import { Amplify } from 'aws-amplify'
import { Toaster } from 'sonner'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

Amplify.configure(outputs)

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
        <Toaster position='top-right' />
      </body>
    </html>
  )
}
